### ISSUE TITLE
Unable to resolve module when using path alias in environment with ESModule and TypeScript 

### ISSUE THREAD

**Issue by yupix** [xHomu/remix-v2-server#5]
Hello! First of all, thank you for your wonderful project. I'm having some problems using this template, so if you know where I can find a solution, could you please let me know?

In an environment using TypeScript and ESModule, importing using the path alias set on `tsconfig.json` gives the following error and does not work properly. 

```
/home/yupix/works/remix-v2-server/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.3.63_@types+node@20.8.4_typescript@5.0.4/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
        ^
Error: Cannot find package '~' imported from /home/yupix/works/remix-v2-server/build/index.js
    at packageResolve (/home/yupix/works/remix-v2-server/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.3.63_@types+node@20.8.4_typescript@5.0.4/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757:9)
    at moduleResolve (/home/yupix/works/remix-v2-server/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.3.63_@types+node@20.8.4_typescript@5.0.4/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:798:18)
    at Object.defaultResolve (/home/yupix/works/remix-v2-server/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.3.63_@types+node@20.8.4_typescript@5.0.4/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /home/yupix/works/remix-v2-server/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.3.63_@types+node@20.8.4_typescript@5.0.4/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/home/yupix/works/remix-v2-server/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.3.63_@types+node@20.8.4_typescript@5.0.4/node_modules/ts-node/src/esm.ts:168:34)
    at /home/yupix/works/remix-v2-server/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.3.63_@types+node@20.8.4_typescript@5.0.4/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/home/yupix/works/remix-v2-server/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.3.63_@types+node@20.8.4_typescript@5.0.4/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/home/yupix/works/remix-v2-server/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.3.63_@types+node@20.8.4_typescript@5.0.4/node_modules/ts-node/src/esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/hooks:833:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:278:30)
Failed running './server.ts'
```

### Projects I have tested

https://github.com/yupix/remix-v2-server/tree/esm-server.ts

### Environment

OS: Ubuntu 22.04.3
Remix: v2.0.1
pnpm: v8.6.7
node: v20.8.0

**Comment by xHomu** [comment]
Hi there, there appears to be a bug with the latest version of @swc/core that caused the error. For now, please fix your @swc/core to 1.3.82:

In package.json:

`    "@swc/core": "1.3.82",`

I'll dig further into this over the weekend, sorry for the hiccup!

**Comment by yupix** [comment]
Thanks for your quick reply. I changed `@swc/core` to `1.3.82` and still get the same error. I have also updated the repositories I am testing. I'll be waiting for the weekend.

**Comment by xHomu** [comment]
Try deleting your pnpm-lock and run `pnpm install; pnpm run dev` again.

**Comment by yupix** [comment]
I deleted `pnpm-lock.yaml` and ran `pnpm i`, but it does not seem to change. Also, I forgot to commit `pnpm-lock.yaml` to the repository, so I committed it.

**Comment by xHomu** [comment]
That's really strange. I am testing on Windows and Mac environment and they worked fine here, so I wonder if there's something specific with swc's Linux kernel that's broken. You can try an older version like 1.3.78 and see if that get it working again.

I'll look into migrating the template to `tsx` instead of `ts-node`, hopefully that would sidestep this issue altogether. Sorry for the trouble!

**Comment by yupix** [comment]
After changing to `1.3.78`, I removed the lock and reinstalled using the same procedure as before, but the error does not seem to change.

**Comment by yupix** [comment]
I have also checked the operation on Windows, but the error seems to occur in the same way as with Linux.

### How to reproduce

```
git clone https://github.com/yupix/remix-v2-server.git
git checkout esm-server.ts

pnpm i
pnpm dev
pnpm dev
```

### Error Details

```
C:\Users\yupix\Desktop\wok\test\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.78_@types+node@20.8.5_typescript@5.0.4\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:757
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
        ^
Error: Cannot find package '~' imported from C:\Users\yupix\Desktop\wok\test\build\index.js
    at packageResolve (C:\Users\yupix\Desktop\wok\test\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.78_@types+node@20.8.5_typescript@5.0.4\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:757:9)
    at moduleResolve (C:\Users\yupix\Desktop\wok\test\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.78_@types+node@20.8.5_typescript@5.0.4\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:798:18)
    at Object.defaultResolve (C:\Users\yupix\Desktop\wok\test\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.78_@types+node@20.8.5_typescript@5.0.4\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:912:11)
    at C:\Users\yupix\Desktop\wok\test\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.78_@types+node@20.8.5_typescript@5.0.4\node_modules\ts-node\src\esm.ts:218:35
    at entrypointFallback (C:\Users\yupix\Desktop\wok\test\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.78_@types+node@20.8.5_typescript@5.0.4\node_modules\ts-node\src\esm.ts:168:34)
    at C:\Users\yupix\Desktop\wok\test\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.78_@types+node@20.8.5_typescript@5.0.4\node_modules\ts-node\src\esm.ts:217:14
    at addShortCircuitFlag (C:\Users\yupix\Desktop\wok\test\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.78_@types+node@20.8.5_typescript@5.0.4\node_modules\ts-node\src\esm.ts:409:21)
    at resolve (C:\Users\yupix\Desktop\wok\test\node_modules\.pnpm\ts-node@10.9.1_@swc+core@1.3.78_@types+node@20.8.5_typescript@5.0.4\node_modules\ts-node\src\esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/hooks:833:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:278:30)
Failed running './server.ts'
```

### Environment

OS: Windows 11 Pro 22621.2361
pnpm: v8.8.0
node: v20.8.0

**Comment by xHomu** [comment]
I have started working the switch to tsx, you can observe the progress on this branch:

https://github.com/xHomu/remix-v2-server/tree/tsx

Feel free to test it out and let me know if it works for you!

**Comment by yupix** [comment]
I think it is very cool to tsx, but the error still seems to be the same. Do you get any errors with imports like `import { say_hello } from "~/utils/hello.js"` in your environment?

Also, importing using relative paths works fine, but the paths that can be set on tsconfig do not seem to be resolving properly.

**Comment by xHomu** [comment]
Yes, aliasing works just fine in my environment:

![image](https://github.com/xHomu/remix-v2-server/assets/84349818/a24b9dac-ab93-41a1-992f-7b5f73587e2b)

I'm quite confused and having trouble nailing down what might be causing all these issues for you. 

* Does the default template `npx create-remix` have the same issues for you?
* What about the Epic-Stack? https://github.com/epicweb-dev/epic-stack/blob/main/docs/getting-started.md

**Comment by yupix** [comment]
<img width="651" alt="image" src="https://github.com/xHomu/remix-v2-server/assets/50538210/437b9a2e-62fa-4f63-a492-c79180b529fd">
<img width="237" alt="image" src="https://github.com/xHomu/remix-v2-server/assets/50538210/2a2da0f0-fba0-4d56-8403-6a3ae7b8b21c">

Thank you for your reply. I just wanted to let you know that I noticed that if you do not give the extension (.js) when importing, an error is displayed on the editor, but Remix works fine without error.

As far as I know, when using ES Module in TypeScript, the import must specify the extension `js`, is this wrong?

https://github.com/microsoft/TypeScript/issues/40878

**Comment by xHomu** [comment]
You're correct. ESM requires the extension. I was working on the wrong branch when testing above, import { Hello } from "~/utils/hello.js"` is the right syntax.

**Comment by yupix** [comment]
I have found that by setting the extension to `.ts` instead of `.js`, there are no errors on the editor, and the remix seems to work correctly. I see that the epic stack you mentioned also specifies `.ts`. Is it common to specify `.ts` instead of `.js`?

**Comment by xHomu** [comment]
.js should work as long as you have `allowJs": true` in tsconfig.

It's worth mentioning though that technically, when you're exporting React Components, you should be using .tsx and .jsx file extensions instead of the .js javascript extension or the .ts typescript extension.

**Comment by yupix** [comment]
You are certainly right about the use of different extensions. This time, hello.ts only provides a function `say_hello` to output `Hello World` using console.log, so I used `ts`. I'm going to close this Issue for now, since it seems that specifying the extension as it is will solve the problem. Thank you for your time. Have a nice weekend!
